import React,{useCallback,useEffect,useState} from 'react';
import {Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {AppModal,Field,ModalButton} from '@/components/Forms';import {Card,EmptyState,PrimaryButton} from '@/components/ui';import {useApp} from '@/context/AppContext';import {supabase} from '@/lib/supabase';import {colors} from '@/lib/theme';
type Item={id:string;item_name:string;quantity:number|null;unit:string|null;estimated_price:number|null;checked:boolean};
export default function Shopping(){const{householdId}=useApp();const[listId,setListId]=useState<string|null>(null);const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(false);const[modal,setModal]=useState(false);const[name,setName]=useState('');const[qty,setQty]=useState('1');const[unit,setUnit]=useState('');const[price,setPrice]=useState('');
const ensureList=useCallback(async()=>{if(!householdId)return null;const{data,error}=await supabase.from('shopping_lists').select('id').eq('household_id',householdId).eq('status','open').order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(data?.id)return data.id;const{data:created,error:ce}=await supabase.from('shopping_lists').insert({household_id:householdId,name:'Courses de la semaine',status:'open'}).select('id').single();if(ce)throw ce;return created.id},[householdId]);
const load=useCallback(async()=>{if(!householdId)return;setLoading(true);try{const id=await ensureList();setListId(id);if(id){const{data,error}=await supabase.from('shopping_list_items').select('*').eq('shopping_list_id',id).order('checked',{ascending:true});if(error)throw error;setItems((data||[]) as Item[])}}catch(e){console.error(e)}finally{setLoading(false)}},[householdId,ensureList]);useEffect(()=>{load()},[load]);
async function add(){if(!listId||!name.trim())return;const{error}=await supabase.from('shopping_list_items').insert({shopping_list_id:listId,item_name:name.trim(),quantity:Number(qty)||1,unit:unit||null,estimated_price:price?Number(price):null,checked:false});if(error)alert(error.message);else{setName('');setQty('1');setUnit('');setPrice('');setModal(false);load()}}
async function toggle(x:Item){const{error}=await supabase.from('shopping_list_items').update({checked:!x.checked}).eq('id',x.id);if(error)alert(error.message);else setItems(v=>v.map(i=>i.id===x.id?{...i,checked:!i.checked}:i))}
async function complete(){if(!listId)return;if(!confirm('Terminer cette liste de courses et en créer une nouvelle ?'))return;const{error}=await supabase.from('shopping_lists').update({status:'completed'}).eq('id',listId);if(error)alert(error.message);else{setListId(null);setItems([]);await load()}}
const total=items.filter(x=>!x.checked).reduce((a,b)=>a+Number(b.estimated_price||0),0);return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={s.c}><Text style={s.h}>Courses</Text><Text style={s.p}>Liste partagée et enregistrée dans Supabase.</Text><Card><Text style={s.total}>Reste estimé : {total.toFixed(2)} €</Text><Text style={s.small}>{items.filter(x=>x.checked).length} article(s) coché(s) sur {items.length}</Text></Card><View style={{marginTop:12}}><PrimaryButton label="Ajouter un article" onPress={()=>setModal(true)}/></View>{items.length===0&&<View style={{marginTop:12}}><EmptyState>La liste est vide.</EmptyState></View>}{items.map(x=><Pressable key={x.id} onPress={()=>toggle(x)}><Card style={{marginTop:10,opacity:x.checked?.55:1}}><View style={s.row}><Text style={s.check}>{x.checked?'✓':'○'}</Text><View style={{flex:1}}><Text style={s.name}>{x.item_name}</Text><Text style={s.small}>{Number(x.quantity||1)} {x.unit||''}</Text></View><Text style={s.price}>{x.estimated_price!=null?`${Number(x.estimated_price).toFixed(2)} €`:'—'}</Text></View></Card></Pressable>)}{items.length>0&&<View style={{marginTop:16}}><PrimaryButton label="Terminer mes courses" onPress={complete}/></View>}</ScrollView><AppModal visible={modal} title="Ajouter un article" onClose={()=>setModal(false)}><Field label="Article" value={name} onChangeText={setName}/><Field label="Quantité" value={qty} onChangeText={setQty} keyboardType="decimal-pad"/><Field label="Unité" value={unit} onChangeText={setUnit}/><Field label="Prix estimé (€)" value={price} onChangeText={setPrice} keyboardType="decimal-pad"/><ModalButton label="Ajouter à la liste" onPress={add}/></AppModal></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},c:{padding:18,maxWidth:900,width:'100%',alignSelf:'center'},h:{fontSize:30,fontWeight:'900',color:colors.brown},p:{color:colors.muted,marginTop:6,marginBottom:16},total:{fontSize:22,fontWeight:'900',color:colors.terracotta},small:{fontSize:12,color:colors.muted,marginTop:4},row:{flexDirection:'row',alignItems:'center',gap:12},check:{fontSize:24,color:colors.sage},name:{fontWeight:'800',color:colors.brown,fontSize:16},price:{fontWeight:'900',color:colors.brown}})
