import React,{useCallback,useEffect,useState} from 'react';
import {Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {AppModal,Field,ModalButton} from '@/components/Forms';
import {Card,EmptyState,PrimaryButton} from '@/components/ui';
import {useApp} from '@/context/AppContext';
import {daysUntil,formatDate} from '@/lib/date'; import {supabase} from '@/lib/supabase'; import {colors} from '@/lib/theme';

type Item={id:string;custom_name:string|null;quantity:number;unit:string|null;location:string;expiry_date:string|null;low_stock_threshold:number|null;products?:{name:string}|null};
export default function Stock(){const{householdId}=useApp();const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(false);const[modal,setModal]=useState(false);const[name,setName]=useState('');const[qty,setQty]=useState('1');const[unit,setUnit]=useState('unité');const[location,setLocation]=useState('pantry');const[expiry,setExpiry]=useState('');const[threshold,setThreshold]=useState('');
const load=useCallback(async()=>{if(!householdId)return;setLoading(true);const{data,error}=await supabase.from('inventory_items').select('id,custom_name,quantity,unit,location,expiry_date,low_stock_threshold,products(name)').eq('household_id',householdId).order('expiry_date',{ascending:true,nullsFirst:false});if(error)console.error(error);else setItems((data||[]) as any);setLoading(false)},[householdId]);useEffect(()=>{load()},[load]);
async function add(){if(!householdId||!name.trim())return;const{error}=await supabase.from('inventory_items').insert({household_id:householdId,custom_name:name.trim(),quantity:Number(qty)||1,unit:unit||null,location,expiry_date:expiry||null,low_stock_threshold:threshold?Number(threshold):null});if(error)alert(error.message);else{setName('');setQty('1');setExpiry('');setThreshold('');setModal(false);load()}}
async function remove(id:string){if(!confirm('Supprimer ce produit du stock ?'))return;const{error}=await supabase.from('inventory_items').delete().eq('id',id);if(error)alert(error.message);else load()}
return <SafeAreaView style={s.safe}><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={s.c}><Text style={s.h}>Stock</Text><Text style={s.p}>Les données ci-dessous viennent de votre table Supabase.</Text><PrimaryButton label="Ajouter un produit" onPress={()=>setModal(true)}/>{items.length===0&&<View style={{marginTop:12}}><EmptyState>Votre stock est vide. Ajoutez votre premier produit.</EmptyState></View>}{items.map(x=>{const d=daysUntil(x.expiry_date);const low=x.low_stock_threshold!=null&&Number(x.quantity)<=Number(x.low_stock_threshold);const nm=x.products?.name||x.custom_name||'Produit';return <Card key={x.id} style={{marginTop:10}}><View style={s.row}><View style={{flex:1}}><Text style={s.name}>{nm}</Text><Text style={s.meta}>{Number(x.quantity)} {x.unit||''} · {x.location}</Text><Text style={s.meta}>Péremption : {formatDate(x.expiry_date)}</Text></View><View style={{alignItems:'flex-end'}}>{d!=null&&<Text style={[s.exp,d<=7&&{color:colors.red}]}>{d<0?'dépassé':d===0?'aujourd’hui':`${d} j`}</Text>}{low&&<Text style={s.low}>stock faible</Text>}<Pressable onPress={()=>remove(x.id)}><Text style={s.delete}>Supprimer</Text></Pressable></View></View></Card>})}</ScrollView><AppModal visible={modal} title="Ajouter au stock" onClose={()=>setModal(false)}><Field label="Produit" value={name} onChangeText={setName} placeholder="Ex. Yaourts"/><Field label="Quantité" value={qty} onChangeText={setQty} keyboardType="decimal-pad"/><Field label="Unité" value={unit} onChangeText={setUnit} placeholder="g, kg, L, unité..."/><Field label="Emplacement" value={location} onChangeText={setLocation} placeholder="fridge / freezer / pantry / other"/><Field label="Date de péremption (AAAA-MM-JJ)" value={expiry} onChangeText={setExpiry}/><Field label="Seuil stock faible" value={threshold} onChangeText={setThreshold} keyboardType="decimal-pad"/><ModalButton label="Ajouter" onPress={add}/></AppModal></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.cream},c:{padding:18,maxWidth:900,width:'100%',alignSelf:'center'},h:{fontSize:30,fontWeight:'900',color:colors.brown},p:{color:colors.muted,marginTop:6,marginBottom:16},row:{flexDirection:'row',justifyContent:'space-between',gap:12},name:{fontSize:16,fontWeight:'800',color:colors.brown},meta:{marginTop:5,color:colors.muted},exp:{fontWeight:'800',color:colors.sage},low:{fontSize:11,color:colors.honey,marginTop:4,fontWeight:'800'},delete:{fontSize:12,color:colors.red,marginTop:10,fontWeight:'800'}})
